---
apiVersion: v1
data:
  ox-admin-password: bXlzZWNyZXQx
kind: Secret
metadata:
  name: ox-admin-password
  namespace: ox
type: Opaque
---
apiVersion: v1
data:
  ox-db-password: bXlzZWNyZXQx
kind: Secret
metadata:
  name: ox-db-password
  namespace: ox
type: Opaque
---
apiVersion: v1
data:
  ox-master-password: bXlzZWNyZXQx
kind: Secret
metadata:
  name: ox-master-password
  namespace: ox
type: Opaque
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mariadb
  namespace: ox
  labels:
    app: mariadb
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mariadb
  template:
    metadata:
      labels:
        app: mariadb
    spec:
      containers:
        - name: mariadb
          image: docker.io/library/mariadb:latest
          ports:
            - containerPort: 3306
          env:
            - name: MARIADB_ROOT_PASSWORD
              value: "root_password"
            - name: MARIADB_USER
              value: "openxchange"
            - name: MARIADB_DATABASE
              value: "oxdata"
            - name: MARIADB_PASSWORD
              value: "db_password"
---
apiVersion: v1
kind: Service
metadata:
  name: mariadb
  namespace: ox
spec:
  selector:
    app: mariadb
  ports:
    - protocol: TCP
      port: 3306
      targetPort: 3306
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: ox-logs
  namespace: ox
spec:
  storageClassName: standard
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 500Mi
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: ox-share
  namespace: ox
spec:
  storageClassName: standard
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 500Mi
# ---
# kind: PersistentVolumeClaim
# apiVersion: v1
# metadata:
#   name: ox-etc
#   namespace: ox
# spec:
#   storageClassName: standard
#   accessModes:
#     - ReadWriteOnce
#   resources:
#     requests:
#       storage: 500Mi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/name: ox
  name: ox
  namespace: ox
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: ox
  template:
    metadata:
      labels:
        app.kubernetes.io/name: ox
    spec:
      containers:
        - name: oxspell
          image: docker.io/jamesregis/open-xchange-spellcheck:latest
          ports:
            - containerPort: 8003
        - name: dcs
          image: docker.io/jamesregis/open-xchange-dcs:latest
          ports:
            - containerPort: 61616
          env:
            - name: OX_DCSDB_DB_PASSWORD
              value: "this-is-my-dcs-password"
            - name: OX_DCSDB_DB_USER
              value: dcsdb_user
            - name: OX_DCSDB_DB_HOST
              value: "mariadb"
        - name: appsuite
          image: docker.io/jamesregis/open-xchange-appsuite:latest
          ports:
            - containerPort: 80
          volumeMounts:
            - mountPath: /ox/etc
              name: share
              readOnly: false
              subPath: ox-appsuite/etc
            - mountPath: /var/opt/filestore
              name: share
              subPath: ox-appsuite/data
            # - mountPath: /opt/open-xchange/etc
            #   name: etc
            # - mountPath: /opt/open-xchange/appsuite/apps/themes
            #   name: share
            #   subPath: ox-appsuite/themes
            - mountPath: /var/log/open-xchange
              name: logs
            - mountPath: /var/log/
              name: logs
            - name: ox-db-password
              mountPath: /run/secrets/ox-db-password
              subPath: ox-db-password
            - name: ox-admin-password
              mountPath: /run/secrets/ox-admin-password
              subPath: ox-admin-password
            - name: ox-master-password
              mountPath: /run/secrets/ox-master-password
              subPath: ox-master-password
          env:
            - name: OX_CONFIG_DB_HOST
              value: "mariadb"
            - name: OX_SERVER_MEMORY
              value: "1024"
            # - name: OX_CONFIG_DB_NAME
            #   value: oxdata
            - name: OX_DB_PASSWORD
              value: "db_password"
            - name: OX_CONFIG_DATABASE_USER
              value: openxchange
            # - name: OX_MASTER_PASSWORD
            #   value: "admin_master_password"
            - name: OX_SERVER_NAME
              value: oxserver
            - name: OX_ADMIN_MASTER_LOGIN
              value: "oxadminmaster"
            - name: OX_ADMIN_MASTER_PASSWORD
              value: "admin_master_password"
            - name: OX_DATADIR
              value: "/var/opt/filestore"
            - name: OX_CONTEXT_ADMIN_EMAIL
              value: "admin@domain"
            - name: OX_ADMIN_PASSWORD
              value: "admin_password"
            - name: OX_CONTEXT_ADMIN_LOGIN
              value: "oxadmin"
            - name: OX_DCSDB_DB_PASSWORD
              value: "this-is-my-dcs-password"
            - name: OX_DCSDB_DB_USER
              value: dcsdb_user
            - name: OX_DCSDB_DB_HOST
              value: "mariadb"
            - name: TZ
              value: "America/Toronto"
      volumes:
        - name: share
          persistentVolumeClaim:
            claimName: ox-share
        - name: logs
          persistentVolumeClaim:
            claimName: ox-logs
        # - name: etc
        #   persistentVolumeClaim:
        #     claimName: ox-etc
        - name: ox-db-password
          secret:
            secretName: ox-db-password
        - name: ox-admin-password
          secret:
            secretName: ox-admin-password
        - name: ox-master-password
          secret:
            secretName: ox-master-password
---
apiVersion: v1
kind: Service
metadata:
  name: rocky
  namespace: ox
spec:
  selector:
    app.kubernetes.io/name: ox
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 80
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ox
  namespace: ox
spec:
  rules:
  - http:
      paths:
      - pathType: Prefix
        path: /
        backend:
          service:
            name: rocky
            port:
              number: 8080
